### ISSUE TITLE
ArchivesSpace: item-level descriptions missing from the HTML export of the Corse papers EAD.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/archivesspace_scripts#1]
Item-level descriptions at the item level (in this case the list of glass lantern slides) are missing from series II, box 2, folders 1, 2, 3, etc.

Compare the UPenn's version of the finding aid at http://hdl.library.upenn.edu/1017/d/pacscl/SCIHIST_GB9441USpaphchf with ours at https://archives.sciencehistory.org/GB94-41.html#listings .

**Comment by jrochkind** [comment]
I am curious if changing to what's built into AS will make the problem better... or worse.

**Comment by eddierubeiz** [comment]
When you have a moment, can you confirm that this problem doesn't exist in the public user interface, @archivistsarah ?

**Comment by eddierubeiz** [comment]
Thanks for checking!

**Comment by eddierubeiz** [comment]
Sarah confirms that this problem is fixed -- and won't come back in the hosted ASpace PUI. I'm closing this issue.
