### ISSUE TITLE
Corse EAD: certain controlled access headings not appearing on our local HTML finding aid

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/archivesspace_scripts#19]
Comparing
- The  [PACSCL finding aid](http://dla.library.upenn.edu/dla/pacscl/detail.html?id=PACSCL_SCIHIST_GB9441USpaphchf) to
- [our own finding aid 
](https://archives.sciencehistory.org/GB94-41.htm)

shows that the PACSCL version has a Controlled Access Headings section that contains agent records such as corporate names (`Eli Lilly and Company`; `Lilly Research Laboratories`) and personal names (`Woodward, R.B. (Robert Burns), 1917-1979`).

These are generated from the following chunk of XML in [our ead](https://archives.sciencehistory.org/ead/scihist-GB94-41.xml) :
```xml
<controlaccess>
    <subject authfilenumber="sh85014262" source="lcsh">Biosynthesis</subject>
    <subject authfilenumber="sh2010105392" source="lcsh">Penicillin -- History</subject>
    <genreform source="aat">Archival materials</genreform>
    <genreform authfilenumber="Lantern slides" source="lcsh">Lantern slides</genreform>
    <corpname authfilenumber="n82137073" rules="dacs" source="naf">Eli Lilly and Company</corpname>
    <persname authfilenumber="n82125720" rules="dacs" source="naf">Woodward, R.B. (Robert Burns), 1917-1979</persname>
    <corpname authfilenumber="n86081432" rules="dacs" source="naf">Lilly Research Laboratories</corpname>
</controlaccess>
```

@archivistsarah , I have a few related questions about this:

- Is this a problem with our XSLT file? ( I think it might be.)
- Can we prove that the PUI will in fact show this info ? ( I think it will)
- Is this worth fixing between now and our planned shift to the hosted ArchivesSpace setup with the PUI next summer? (maybe, maybe not.)

**Comment by archivistsarah** [comment]
It is a problem with the XSLT (which is set for some reason to only pull subject headings that have source = LCSH). It's an easy fix, so I'll update the file and submit a pull request.

**Comment by eddierubeiz** [comment]
Fantastic.

**Comment by eddierubeiz** [comment]
All 7 headings now appear at https://archives.sciencehistory.org/GB94-41.html#subjects . Thank you @archivistsarah !
