### ISSUE TITLE
Heroku project to export EADs from ArchivesSpace to S3

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/archivesspace_scripts#26]
- Research whether Heroku can do this at all, and how much it will cost us.
- Write a script in Ruby to do the export (based on existing shell script)
- Provide software and credentials so the script can make HTTP calls to the API, parse XML and json, and upload files to S3
- Create an S3 bucket where U Penn and CHSTM can harvest the XML
- Set up a cname to point at the new bucket.
- Set up the script to run weekly, harvesting the EADS and saving them in the s3 bucket.
- Document exhaustively in the wiki

Out of scope: actual communication with CHSTM and U Penn and getting them to harvest the items from the new location.

**Comment by eddierubeiz** [comment]
This is part of ref #17

**Comment by eddierubeiz** [comment]
This is done. [The project](https://github.com/sciencehistory/export_archivesspace_xml) is documented at https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/2151514113/export+archivesspace+xml .

**Comment by jrochkind** [comment]
It's sort of done, I would say the project isn't done until #29 is done, but ok to close this ticket, and thanks very much for documenting the remainder in #29. 

How soon can we get #29 done? I really don't like leaving these things hanging indefinitely, they tend to become much harder to deal with after the details aren't fresh in our minds, and easy to forget to deal with them until well after they should have been dealt with. 

Are our partners harvesting EAD from new location yet, and if not, why not and how soon can they be?

**Comment by eddierubeiz** [comment]
One is; the other was delayed in making the change for infrastructure reasons indirectly due to the pandemic. I won't post specifics on here but we can discuss on Monday. I believe we can get this all wrapped up next week.
