### ISSUE TITLE
Download ead files from s3, instead of getting them out of ArchivesSpace

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/archivesspace_scripts#27]
The new Heroku project at https://github.com/sciencehistory/export_archivesspace_xml is in charge of exporting our EADs to S3.
Just download them from s3 via `wget` and create the HTML files based on that, instead of duplicating the functionality here.

**Comment by jrochkind** [comment]
@eddierubeiz Add that repo to our Zenhub, and start filing tickets there instead of here?  But I guess it actually doens't matter too much, this is just fine too. 

At some point maybe we'll switch to using the github built-in new project board, which might simplify this management too.
