### ISSUE TITLE
Daylight savings time change triggered database connection bug.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/archivesspace_scripts#3]
**PROBLEM:**
This morning the front end was unable to connect to the database on account of a 
`Java::JavaSql::SQLException: HOUR_OF_DAY: 2 -> 3`
error.

**FIX:**
In `/opt/archivesspace/config/config.rb`, the `AppConfig[:db_url]` setting specifies: 
`&serverTimezone=America/New_York`.
I changed this to `serverTimezone=UTC` and restarted the ArchivesSpace daemon, and was able to log in again.

**Comment by eddierubeiz** [comment]
See also:
https://groups.google.com/g/archivesspace/c/iKeztw0N1Fs
https://bugs.mysql.com/bug.php?id=96276
https://bugs.mysql.com/bug.php?id=82005

**Comment by jrochkind** [comment]
And one more from aspace mailing list, although it doens't really have an answer. Seems like this is a known problem nobody knwos the "right" answer to. 

http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2021-March/008275.html
