### ISSUE TITLE
unpublish all digital objects

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/archivesspace_scripts#33]
Ahead of the switch to a hosted PUI, can you unpublish all digital objects? This would need to be done by the end of June, which is roughly when we're expecting to switch to a hosted instance and start using the PUI. 

Example digital object URI: /repositories/3/digital_objects/1634

**Comment by eddierubeiz** [comment]
It appears this can't be done via the API, so I ran the following against the database:

```sql
mysql> select id, repo_id, publish, suppressed from digital_object where repo_id = 3 and publish = 0;
+------+---------+---------+------------+
| id   | repo_id | publish | suppressed |
+------+---------+---------+------------+
| 2529 |       3 |       0 |          0 |
| 2530 |       3 |       0 |          0 |
| 2531 |       3 |       0 |          0 |
| 2532 |       3 |       0 |          0 |
| 2533 |       3 |       0 |          0 |
| 2534 |       3 |       0 |          0 |
| 2535 |       3 |       0 |          0 |
| 2539 |       3 |       0 |          0 |
| 2540 |       3 |       0 |          0 |
| 2538 |       3 |       0 |          0 |
| 2536 |       3 |       0 |          0 |
| 2537 |       3 |       0 |          0 |
+------+---------+---------+------------+

mysql> update digital_object set publish = 0  where repo_id = 3;
Query OK, 2492 rows affected (0.02 sec)
Rows matched: 2504  Changed: 2492  Warnings: 0


```

**Comment by eddierubeiz** [comment]
This worked, but [search results](https://archives.sciencehistory.org/digital_objects?filter_term[]={%22publish%22:%22true%22}) were unchanged.
- Tried a soft reindex (following [ArchivesSpace indexing docs](https://archivesspace.github.io/tech-docs/administration/indexes.html) ) to no avail.
- Trying a hard reindex; that did work.
