### ISSUE TITLE
Remove duplicate files

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/archivesspace_scripts#5]
Certain files (e.g. the `xsl` transform, which is present in both `master/fa-files` and in `master/finding-aid-files`) are present twice. I'm fairly certain only one of the copies is actually being used.
Get rid of the excess files.

**Comment by archivistsarah** [comment]
I don't think fa-files is the in use directory because it doesn't contain the image files appearing in the header (as of 9/2)

**Comment by eddierubeiz** [comment]
Duplicate of #8
